### ISSUE TITLE
ValueError: need more than 4 values to unpack

### ISSUE THREAD

**Issue by nanxintin** [coreylynch/async-rl#14]
When I try to run the a3c.py, I came across some problem.
“”“
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "a3c.py", line 71, in actor_learner_thread
    s, a, R, minimize, p_network, v_network = graph_ops
ValueError: need more than 4 values to unpack
“‘’”
Follow by the solution in the Stackoverflow, I add a comma in the code. but it failed.
I would appreciate it if anyone can help me.

**Comment by fgvbrt** [comment]
It looks like a3c is currently in progress and it shouldn't be working.  As you can see build_graph https://github.com/coreylynch/async-rl/blob/master/a3c.py#L170 returns 4 values but then you trying to unpack it with 6 values https://github.com/coreylynch/async-rl/blob/master/a3c.py#L70

**Comment by nanxintin** [comment]
@fgvbrt Thank you for your reply and you are right. It seems that the author is too busy to update the A3C project in the short term.
